version: "3.6"

services:
  batch-server:
    container_name: batch-server
    build: .
    volumes:
      - $HOME/.aws/:/root/.aws/
      - ./:/var/task/
    ports:
      - "9000:8080"
    networks:
      - laravel_sail
      - docker_lamp_2_default
    env_file:
      - .env.local
networks:
  laravel_sail:
    external: true
  docker_lamp_2_default:
    external: true